---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nurupo.
--- DateTime: 2020/4/26 18:27
---
isPlayingLoadingBGM = false
function downloadGUI()
    if not isPlayingLoadingBGM then
        playSound3D ("https://archive.sparrow.moe/mp3/title.mp3", 0, 0, 0, true)
        isPlayingLoadingBGM = true
    end
end
addEventHandler("onClientRender", root, downloadGUI)

function checkTransfer()
    if isTransferBoxActive() == true then
        setTimer(checkTransfer,2000,1) -- Check again after 2 seconds
    else
        removeEventHandler("onClientRender", root, downloadGUI)
        isPlayingLoadingBGM = false
    end
end
addEventHandler("onClientResourceStart",resourceRoot,checkTransfer)