GUIEditor_Window = {}
GUIEditor_Button = {}
GUIEditor_Label = {}
GUIEditor_Scrollbar = {}
GUIEditor_Window[1] = guiCreateWindow(320, 250, 155, 290, "By: #IBIZA ", false)
GUIEditor_Scrollbar[1] = guiCreateScrollBar(11, 49, 425, 16, true, false, GUIEditor_Window[1])
GUIEditor_Label[1] = guiCreateLabel(54, 30, 435, 15, "HOOD", false, GUIEditor_Window[1])
guiSetFont(GUIEditor_Label[1], "sans")
guiLabelSetColor(GUIEditor_Label[1], 0 , 255 , 0)
GUIEditor_Label[2] = guiCreateLabel(48, 75, 435, 15, "DOOR 1", false, GUIEditor_Window[1])
guiSetFont(GUIEditor_Label[2], "sans")
guiLabelSetColor(GUIEditor_Label[2], 255 , 255 , 0)
GUIEditor_Scrollbar[2] = guiCreateScrollBar(11, 91, 425, 16, true, false, GUIEditor_Window[1])
GUIEditor_Label[3] = guiCreateLabel(48, 112, 435, 15, "DOOR 2", false, GUIEditor_Window[1])
guiSetFont(GUIEditor_Label[3], "sans")
guiLabelSetColor(GUIEditor_Label[3], 30 , 144 , 255)
GUIEditor_Scrollbar[3] = guiCreateScrollBar(11, 130, 425, 16, true, false, GUIEditor_Window[1])
GUIEditor_Label[4] = guiCreateLabel(48, 151, 435, 15, "DOOR 3", false, GUIEditor_Window[1])
guiSetFont(GUIEditor_Label[4], "sans")
guiLabelSetColor(GUIEditor_Label[4], 0 , 255 , 0)
GUIEditor_Scrollbar[4] = guiCreateScrollBar(11, 168, 425, 16, true, false, GUIEditor_Window[1])
GUIEditor_Label[5] = guiCreateLabel(48, 189, 435, 15, "DOOR 4", false, GUIEditor_Window[1])
guiSetFont(GUIEditor_Label[5], "sans")
guiLabelSetColor(GUIEditor_Label[5], 255 , 255 , 0)
GUIEditor_Scrollbar[5] = guiCreateScrollBar(11, 206, 425, 16, true, false, GUIEditor_Window[1])
GUIEditor_Label[6] = guiCreateLabel(35, 226, 435, 15, "DOOR MALA", false, GUIEditor_Window[1])
guiSetFont(GUIEditor_Label[6], "sans")
guiLabelSetColor(GUIEditor_Label[6], 30 , 144 , 255)
GUIEditor_Scrollbar[6] = guiCreateScrollBar(11, 243, 425, 16, true, false, GUIEditor_Window[1])
GUIEditor_Button[1] = guiCreateButton(11, 265, 330, 14, ">CLOSE<", false, GUIEditor_Window[1])
guiSetFont(GUIEditor_Button[1], "sans")
guiWindowSetSizable(GUIEditor_Window[1], false)
setElementData(GUIEditor_Scrollbar[1], "Type", 0)
setElementData(GUIEditor_Scrollbar[2], "Type", 2)
setElementData(GUIEditor_Scrollbar[3], "Type", 3)
setElementData(GUIEditor_Scrollbar[4], "Type", 4)
setElementData(GUIEditor_Scrollbar[5], "Type", 5)
setElementData(GUIEditor_Scrollbar[6], "Type", 1)
guiSetVisible(GUIEditor_Window[1], false)
showCursor(false)
function enableVehicleControl()
  if guiGetVisible(GUIEditor_Window[1]) == false then
    guiSetVisible(GUIEditor_Window[1], true)
    showCursor(true)
  else
    guiSetVisible(GUIEditor_Window[1], false)
    showCursor(false)
  end
end
addCommandHandler("cveh", enableVehicleControl)
bindKey("f3", "down", enableVehicleControl)
function closeButton()
  guiSetVisible(GUIEditor_Window[1], false)
  showCursor(false)
end
addEventHandler("onClientGUIClick", GUIEditor_Button[1], closeButton, false)
function updateRatio(Scrolled)
  local position = guiScrollBarGetScrollPosition(Scrolled)
  local door = getElementData(Scrolled, "Type")
  triggerServerEvent("moveThisShit", getLocalPlayer(), door, position)
end
addEventHandler("onClientGUIScroll", getRootElement(), updateRatio)
